# config.yaml

tools:
  ovitosif: /path/to/ovito.sif
  babel: /opt/babel/bin/babel
  displacement: /opt/babel/bin/displacement
  patternDetect: /opt/babel/bin/patternDetect
  patternInit: /opt/babel/bin/patternInit
